monitor.alsa.rules = [
  {
    matches = [
        {
            device.name = "~alsa_card.*"
        }
    ]
    actions = {
        update-props = {
            api.alsa.use-acp = true
        }
    }
  },
  {
    matches = [
      {
        node.name = "~alsa_input.*"
      },
      {
        node.name = "~alsa_output.*"
      }
    ]
    actions = {
        update-props = {
            api.alsa.period-size = 256
            api.alsa.headroom = 8192
        }
    }
  }
]
