alias config='/usr/bin/git --git-dir=$HOME/.repository/ --work-tree=$HOME'
alias vim='~/.config/bin/launch-vim'
alias l='ls -lah'
alias rm='rm -i'
alias diff='kitty +kitten diff'
alias hosts='sudo vim /etc/hosts'
alias sshconfig='vim $HOME/.ssh/config'
alias wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'
alias kssh='kitty +kitten ssh'
alias mysql-workbench='mysql-workbench --configdir=$XDG_DATA_HOME/mysql/workbench'
