#!/usr/bin/env bash

external_monitor=$(bspc query -M --names | grep -v eDP-1)

case $AUTORANDR_CURRENT_PROFILE in
    dual-*)
        move-desktops-to-monitor "eDP-1" "$external_monitor"
        ;;
    single-*|laptop)
        if [[ $(bspc query -M --names | grep -c eDP-1) = 0 ]]; then
            move-desktops-to-monitor "eDP-1" "$external_monitor"
        else
            move-desktops-to-monitor "$external_monitor" "eDP-1"
        fi
        ;;
    *)
        ;;
esac
