"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$localip\
$shlvl\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$memory_usage\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$status\
$os\
$container\
$shell\
$character"""
right_format = """$time"""

[character]
success_symbol = '[➜](bold green)'
vimcmd_symbol = '[](bold green)'
error_symbol = '[✖](bold red)'
format = '  $symbol '

[directory]
format = '  [$path]($style)[$read_only]($read_only_style) '

[time]
format = '[$time]($style)  '
disabled = false
