#!/usr/bin/env bash

#
# AUTOSTART
#

# autorandr -c maybe?

if [[ "$(query-monitor --primary)" = "DP-1" ]]; then
    xrdb -merge "$HOME/.config/X11/.Xresources.144dpi"
    xinput set-prop 10 'libinput Accel Speed' 0.2
else
    xrdb -merge "$HOME/.config/X11/.Xresources.96dpi"
fi

# Set X11 colorscheme
xrdb -merge "$HOME/.config/colorschemes/current/colors-x11.Xresources"

# Set Wallpaper
source $HOME/.config/bin/set-wallpaper &

# Start compositor
# picom &

# Autostart desktop entries
systemctl --user start autostart-bspwm.target

# Two finger click for right clicking
xinput set-prop "VEN_04F3:00 04F3:32AA Touchpad" "libinput Click Method Enabled" 0 1

# keyboard stuff and lockscreen could be added to autostart-bspwm

setxkbmap -config "$HOME/.config/xkb/config"

# start xplugd
xplugd "$HOME/.config/xplugd/xplugrc"

# Launch lock package
xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock &

# Set last numlock state
numlockx &

# Launch sxhkd
launch-sxhkd

# https://github.com/baskerville/bspwm/issues/811#issuecomment-1546516752
# fix-focusing-bug.sh &

# Launch dunst
cat $HOME/.config/dunst/dunstrc $HOME/.config/colorschemes/current/colors-dunst.dunstrc | dunst -config - &

# Set cursor
xsetroot -cursor_name left_ptr

# border color
source $HOME/.config/colorschemes/current/colors-bspwm.sh

# start nm-applet
/usr/bin/nm-applet &

#
# CONFIGURATION
#

# Desktops
if [ "$(query-monitor -c)" -gt 1 ] && [ "$(query-monitor -m)" = 0 ]; then
    bspc monitor "$(query-monitor --primary)" -d  1 2 3 4 5 6 7 8
    bspc monitor "$(query-monitor --side)"    -d  1 2 3 4 5 6 7 8
else
    bspc monitor primary -d                       1 2 3 4 5 6 7 8
fi

# Config
bspc config border_width                     1
bspc config window_gap                       3
bspc config split_ratio                      0.52
bspc config remove_unplugged_monitors        true
bspc config merge_overlapping_monitors       true

# double borders
# borders &

# Monocle settings
bspc config borderless_monocle               true
bspc config gapless_monocle                  true
#bspc config single_monocle                   true

# Padding
bspc config top_padding                      0
bspc config bottom_padding                   0
bspc config left_padding                     0
bspc config right_padding                    0

# Colors
bspc config normal_border_color              $normal_border_color
bspc config active_border_color              $active_border_color
bspc config focused_border_color             $focused_border_color

# Mouse
#bspc config focus_follows_pointer            true

# Rules
bspc rule -a feh state=floating border=off

# Launch polybar
launch-polybar &
