#!/bin/sh

#
# AUTOSTART
#

# Launch sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Launch polybar
$HOME/.config/polybar/launch.sh &

# Set cursor
xsetroot -cursor_name left_ptr

#
# CONFIGURATION
#

# Desktops
bspc monitor -d                              1 2 3 4 5 6 7 8 9

# Config
bspc config border_width                     0
bspc config window_gap                       10
bspc config split_ratio                      0.50

# Monocle settings
bspc config borderless_monocle               true
bspc config paddingless_monocle              true
bspc config gapless_monocle                  true
#bspc config single_monocle                   true

# Padding
bspc config top_padding                      0
bspc config bottom_padding                   0
bspc config left_padding                     0
bspc config right_padding                    0

# Mouse
#bspc config focus_follows_pointer            true

# Rules
bspc rule -a firefox desktop='^3' follow=on
