#!/bin/sh

#
# AUTOSTART
#

# Set X11 colorscheme
xrdb -merge "$HOME/.config/colorschemes/current/colors-x11.Xresources"

# Set Wallpaper
source $HOME/.config/bin/set-wallpaper &

# Start compositor
picom &

# Autostart desktop entries
systemctl --user start autostart.target

# Set Belgian keyboard layout
setxkbmap us

# Use caps for escape
setxkbmap -option caps:escape

# Set last numlock state
numlockx &

# Launch lock package
xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock &

# Launch sxhkd
launch-sxhkd

# Launch polybar
$HOME/.config/polybar/launch.sh &

# Launch dunst
cat $HOME/.config/dunst/dunstrc $HOME/.config/colorschemes/current/colors-dunst.dunstrc | dunst -config - &

# Set cursor
xsetroot -cursor_name left_ptr

# border color
source $HOME/.config/colorschemes/current/colors-bspwm.sh

# FZF colors
source ${COLORSCHEMES}/current/colors-fzf.sh

#
# CONFIGURATION
#

# Desktops
bspc monitor primary -d                        1 2 3 4 5 6 7 8

# Config
bspc config border_width                     0
bspc config window_gap                       5
bspc config split_ratio                      0.52

# double borders
# borders &

# Monocle settings
bspc config borderless_monocle               true
bspc config gapless_monocle                  true
#bspc config single_monocle                   true

# Padding
bspc config top_padding                      0
bspc config bottom_padding                   0
bspc config left_padding                     0
bspc config right_padding                    0

# Colors
bspc config normal_border_color              $border_color
bspc config active_border_color              $border_color
bspc config focused_border_color             $border_color

# Mouse
#bspc config focus_follows_pointer            true

# Rules
bspc rule -a feh state=floating border=off
