#!/bin/sh

git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim

nvim --headless \
    -c 'autocmd User PackerComplete quitall' \
    -c 'PackerSync'

servers=$(nvim --headless \
    -c 'lua local output=""; for k,v in pairs(require "plugin.lsp") do output = output .. " " .. k end; print(output)' \
    -c q 2>&1)

nvim --headless \
    -c "LspInstall --sync $servers" \
    -c q

exit 0
